name: Update README with Issues

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨 0 点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install

    - name: Fetch Issues and Update README
      env:
        ISSUSE_TOKEN: ${{ secrets.ISSUSE_TOKEN }}
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        REPO_NAMES: ${{ secrets.REPO_NAMES }}
      run: |
        npm run build

    - name: Update target repositories
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        ISSUSE_TOKEN: ${{ secrets.ISSUSE_TOKEN }}
        REPO_NAMES: ${{ secrets.REPO_NAMES }}
      run: |
        IFS=';' read -r -a repoArray <<< "$REPO_NAMES"
        for repo in "${repoArray[@]}"
        do
          echo "Updating $repo"

          # Use the same temporary directory
          git clone https://$GIT_USERNAME:$ISSUSE_TOKEN@github.com/$GIT_USERNAME/$repo.git $repo
          
          # Copy the updated README.md from the temporary directory to the cloned repository
          cp ${repo}_README.md $repo/README.md
          
          # Commit and push changes in the target repository
          cd $repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with issue information" || echo "No changes to commit"
          git push

          # Return to the previous directory and continue
          cd -
        done